[package]
name = "ranked-ref"
version = "0.1.0"
authors = ["Ilya Maximov <mail@overlisted.net>"]
edition = "2018"

[dependencies]
serenity = "0.9.3"
dashmap = "3.11.10"

[dependencies.tokio]
version = "0.2"
features = ["full"]
